# Generated by Django 3.1.3 on 2020-11-12 04:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0))),
                ('provider', models.CharField(choices=[('O1', 'Office 1'), ('O2', 'Office 2'), ('O3', 'Office 3'), ('O4', 'Office 4'), ('O5', 'Office 5')], max_length=3)),
                ('province', models.CharField(choices=[('SJ', 'San Jose'), ('AL', 'Alajuela'), ('CA', 'Cartago'), ('HE', 'Heredia'), ('GU', 'Guanacaste'), ('PU', 'Puntarenas'), ('LI', 'Limon')], max_length=2)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
